version: "3.7"

services:
    app-container:
        container_name: app-container
        build:
            context: ./
            dockerfile: Dockerfile
        command: java -jar /tuatara-demo/target/demo-0.0.1-SNAPSHOT.jar
        ports: 
            - 8080:8080
        networks:
            - ntwrk

    postgres:
        container_name: postgres
        image: postgres:10.0
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - ntwrk
        
networks:
  ntwrk:    
    driver: bridge