version: "3.7"

services:
    postgres:
        container_name: postgres
        image: postgres:10.0
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: email@email
            PGADMIN_DEFAULT_PASSWORD: password